/* ══════════════════════════════════════════
   CSE — 7 Competencias Socioemocionales
   Módulo de Profundización · MEN 2026
   ══════════════════════════════════════════ */

const _cse_data = [

/* ─────────────────────────────────────────
   CSE-1 · Conciencia emocional
───────────────────────────────────────── */
{
  id: 'cse1',
  num: 'CSE-1',
  color: '#534AB7',
  bg: '#EEEDFE',
  tc: '#3C3489',
  icon: 'ti-eye',
  title: 'Conciencia emocional',
  eje: 'Yo conmigo mismo',
  def: 'Capacidad de identificar, nombrar y comprender las propias emociones y las de los demás, reconociendo las señales corporales, cognitivas y contextuales que las generan.',
  secuencia: [
    { fase: 'Apertura (Termómetro de Granularidad)', tiempo: '15 min', desc: 'Rutina de conciencia corporal profunda: los participantes cierran los ojos, respiran pausadamente y ejecutan un escaneo de su cuerpo de pies a cabeza. Deben registrar cartográficamente en qué órganos o músculos se aloja físicamente su estado emocional actual, asignándole un color y una textura metafórica sin emitir juicios.', rol: 'El facilitador guía con voz suave y pausas largas, modelando el ejercicio compartiendo primero su propio estado corporal interno. Protege la seguridad psicológica del grupo.' },
    { fase: 'Exploración conceptual', tiempo: '20 min', desc: 'Análisis del continuum de granularidad emocional: diferenciación técnica entre la emoción de respuesta biológica automática, el sentimiento como elaboración cognitiva y el estado de ánimo sostenido. Uso de la analogía de Nussbaum: las emociones como juicios de valor que revelan lo que consideramos valioso.', rol: 'Docente presenta marcos conceptuales con ejemplos reales extraídos de las crisis escolares cotidianas, promoviendo la expansión del vocabulario emocional del grupo.' },
    { fase: 'Práctica activa (El Diccionario Fisiológico)', tiempo: '25 min', desc: 'Construcción del mapa de sensaciones: en una silueta humana impresa, cada participante mapea la ubicación exacta de emociones primarias y complejas (indignación, vergüenza, orgullo, frustración). Posteriormente, diseñan su libreta personal de bitácora emocional de aula.', rol: 'El facilitador circula por los subgrupos realizando preguntas reflexivas abiertas: ¿Qué pensamientos precedieron a esa opresión en el pecho? ¿Qué conducta automática desató?' },
    { fase: 'Transferencia pedagógica', tiempo: '20 min', desc: 'Grupos por niveles educativos co-diseñan una rutina de sintonía emocional de 5 minutos para implementar al inicio de sus clases. Definen el vocabulario matizado adecuado para las edades y estructuran cómo el docente modelará la rutina exponiendo su propia interioridad de forma regulada.', rol: 'Acompaña el diseño metodológico. Recuerda que la rutina de conciencia debe ser un recurso protector, nunca una obligación invasiva.' },
    { fase: 'Cierre y metacognición', tiempo: '10 min', desc: 'Ronda de salida: cada participante comparte en una única palabra precisa el estado emocional con el que se retira y un hallazgo de autoconciencia relevante. Se da espacio al silencio reflexivo.', rol: 'Recoge las palabras de salida en un mural visual para evaluar el clima final del grupo.' }
  ],
  actividades: [
    { nivel: 'Educación Inicial (0–5 años)', bg: '#E1F5EE', tc: '#085041', items: ['Dado de Granularidad: cubo grande de espuma con expresiones faciales complejas. Los niños lo lanzan, imitan el gesto y narran una historia de un juguete que experimentó esa misma emoción.', 'El monstruo de los colores (Lectura Dialógica): lectura guiada con frascos reales de vidrio donde los niños clasifican lanas de colores según la emoción diaria.', 'Espejo de la Alteridad: en parejas frente a frente, un niño gesticula sutilmente una emoción y su compañero actúa como espejo exacto, intentando adivinar el estado emocional reflejado.'] },
    { nivel: 'Básica Primaria (1°–5°)', bg: '#E6F1FB', tc: '#0C447C', items: ['Semáforo Corporal Diario: registro en una mini-tarjeta antes de iniciar la jornada (Rojo=Inundado, Amarillo=Inquieto, Verde=En calma).', 'Línea de Tiempo de Picos Emocionales: gráfica semanal de montañas y valles que registre eventos del colegio que detonaron alegría, frustración o exclusión.', 'Auditoría Emocional de Cuentos: lectura crítica de un relato identificando los mensajes corporales ocultos de los personajes y cómo el contexto influyó en sus sentimientos.'] },
    { nivel: 'Básica Secundaria (6°–9°)', bg: '#FBEAF0', tc: '#72243E', items: ['Bitácora de Granularidad Emocional: registro escrito que analice — Detonador objetivo + Señal fisiológica corporal + Pensamiento automático + Emoción semántica exacta.', 'Análisis del Lenguaje Juvenil: debate sobre las implicaciones de reducir todo el vocabulario emocional a expresiones genéricas o jergas locales.', 'Lectura de emociones en la historia local: análisis de testimonios de memoria oral comunitaria identificando las emociones subyacentes de los relatos.'] },
    { nivel: 'Media (10°–11°)', bg: '#FAECE7', tc: '#712B13', items: ['Ensayo Argumentativo: "Las emociones como juicios evaluativos de valor en la teoría de Martha Nussbaum aplicada a la justicia escolar colombiana".', 'Investigación de Campo Intercultural: entrevistas a miembros de la comunidad de diversas culturas o generaciones sobre cómo identifican y nombran sus emociones.', 'Producción Audiovisual: micro-podcast de 3 minutos para visibilizar la importancia de la salud mental y la granularidad emocional en la adolescencia contemporánea.'] }
  ],
  rubrica: [
    { criterio: 'Identificación emocional precisa', d: ['Incapaz de reconocer o nombrar estados emocionales propios o del entorno.', 'Identifica emociones básicas únicamente cuando se le interroga con preguntas cerradas directas.', 'Identifica y nombra de forma autónoma una gama variada de emociones primarias utilizando vocabulario matizado.', 'Analiza con fluidez semántica la complejidad de múltiples emociones simultáneas en sí mismo y en los otros en diversos contextos de tensión.'] },
    { criterio: 'Reconocimiento de señales corporales', d: ['Ignora las señales físicas asociadas a sus estados emocionales.', 'Identifica algunas reacciones corporales básicas (sudoración, llanto) con acompañamiento del docente.', 'Describe con precisión las señales corporales internas asociadas a sus emociones de forma regular.', 'Integra de forma autónoma la lectura de sus señales corporales, cognitivas y contextuales para prevenir desbordamientos emocionales.'] },
    { criterio: 'Vocabulario y granularidad semántica', d: ['Reduce toda su expresión emocional a términos genéricos como "bien" o "mal".', 'Utiliza un glosario limitado de emociones básicas (alegría, tristeza, rabia, miedo) de manera repetitiva.', 'Posee un repertorio amplio y diferenciado de términos emocionales (30+ palabras), aplicándolos con precisión.', 'Apropia un vocabulario emocional matizado, culturalmente situado, y desgrana variaciones sutiles de estados de ánimo complejos.'] }
  ],
  guia: {
    prop: 'Garantizar que los docentes desarrollen una alta granularidad emocional y una lectura corporal fina de sus propios estados internos, estructurando andamiajes didácticos viables para transferir esta competencia protectora a las aulas colombianas.',
    adv: [
      'Bajo ninguna circunstancia obligue a un estudiante o participante a exponer públicamente una experiencia emocional traumática o dolorosa.',
      'El facilitador debe modelar el ejercicio exponiendo primero su propia interioridad de forma vulnerable pero regulada.',
      'Evite catalogar las emociones como "positivas" o "negativas"; todas las emociones son legítimas y contienen información valiosa sobre lo que el sujeto valora.',
      'Tenga estructurado un canal de derivación institucional discreto si emerge un caso crítico de salud mental durante los ejercicios.'
    ],
    mat: ['Siluetas impresas del mapa corporal humano', 'Crayones, marcadores o lápices de colores variados', 'Tarjetas didácticas de granularidad y vocabulario emocional', 'Libretas de bitácora personal de autoformación'],
    cierre: 'Concluya con la "Palabra de Salida": cada participante comparte en una palabra el estado emocional con el que se retira. Este ejercicio estabiliza el cierre del grupo, valida la experiencia individual y ofrece datos sobre el clima emocional del taller.'
  }
},

/* ─────────────────────────────────────────
   CSE-2 · Regulación emocional
───────────────────────────────────────── */
{
  id: 'cse2',
  num: 'CSE-2',
  color: '#0F6E56',
  bg: '#E1F5EE',
  tc: '#085041',
  icon: 'ti-adjustments-horizontal',
  title: 'Regulación emocional',
  eje: 'Yo conmigo mismo',
  def: 'Capacidad para manejar, de forma constructiva, ética y adaptativa, las propias emociones en distintas situaciones personales, sociales y escolares, activando estrategias de afrontamiento que transformen estados afectivos intensos en respuestas reflexivas y coherentes con los propios valores.',
  secuencia: [
    { fase: 'Apertura (Escaneo del detonante)', tiempo: '15 min', desc: 'Cada participante recibe una tarjeta con una situación escolar típica generadora de estrés o frustración (una queja de un padre agresivo, un estudiante que interrumpe repetidamente, una instrucción directiva que contradice el criterio pedagógico). Individualmente, mapean su reacción emocional e identifican qué estrategia usarían instintivamente y qué consecuencias tendría.', rol: 'El facilitador crea un clima de honestidad y no-juicio. Modela compartiendo una situación propia en la que la gestión emocional fue un reto real para él o ella.' },
    { fase: 'Exploración conceptual', tiempo: '20 min', desc: 'Presentación del ciclo de regulación emocional: (1) Reconocer el detonante. (2) Identificar la señal corporal. (3) Nombrar la emoción con precisión. (4) Activar la estrategia de afrontamiento (respiración consciente, aplazamiento de respuesta, búsqueda de apoyo). (5) Actuar desde los valores. Diferenciación clave entre suprimir, evitar y regular.', rol: 'Docente presenta el modelo de Gross (2014) con ejemplos concretos del aula colombiana. Enfatiza que regular no es fingir que no se siente: es actuar desde los valores a pesar de lo que se siente.' },
    { fase: 'Práctica activa (Botella de la Calma)', tiempo: '25 min', desc: 'Construcción física de una "Botella de la Calma" (recipiente con agua, glicerina y brillantina) que simboliza el estado de agitación interna y el proceso de sedimentación. Simultaneamente, los participantes elaboran su menú personal de estrategias de regulación: ¿qué funciona para mí cuando siento frustración intensa? ¿y cuando siento angustia? ¿y cuando siento ira?', rol: 'Facilita la reflexión sobre la diferencia entre estrategias de regulación adaptativas (que resuelven sin dañar) y desadaptativas (que alivian momentáneamente pero generan consecuencias). Sin juzgar las estrategias actuales de nadie.' },
    { fase: 'Transferencia pedagógica', tiempo: '20 min', desc: 'Grupos por niveles diseñan un protocolo de "Pausa Emocional" para implementar en el aula cuando ellos mismos o sus estudiantes detecten un estado de desbordamiento. Incluye: señal acordada para la pausa, estrategia de 2-3 minutos y criterio para retomar la actividad.', rol: 'Acompaña el diseño. Recuerda que el docente que modela la pausa emocional sin vergüenza enseña regulación con el cuerpo entero, no con las palabras.' },
    { fase: 'Cierre y metacognición', tiempo: '10 min', desc: 'Cada participante completa en voz alta: "Mi emoción más difícil de regular en el aula es... y la estrategia que me comprometo a probar esta semana es...". Se crea un muro de compromisos visible.', rol: 'Recoge los compromisos sin evaluarlos. Propone un seguimiento en la próxima sesión.' }
  ],
  actividades: [
    { nivel: 'Educación Inicial (0–5 años)', bg: '#E1F5EE', tc: '#085041', items: ['Rincón de la Calma: espacio físico del aula con almohadas, botella de la calma, libros suaves y objetos de textura. Los niños aprenden a identificar cuándo necesitan ir allí.', 'Respiración del Osito: técnica de respiración lenta con un peluche sobre el abdomen — el osito "duerme y se despierta" con cada respiración.', 'El Semáforo de las Emociones: técnica visual donde los niños aprenden a detenerse (rojo), calmarse (amarillo) y actuar (verde) ante situaciones de conflicto o frustración.'] },
    { nivel: 'Básica Primaria (1°–5°)', bg: '#E6F1FB', tc: '#0C447C', items: ['Menú de Estrategias: cada estudiante construye su "menú personal de calma" (tarjetas ilustradas con estrategias que le funcionan a él/ella específicamente).', 'Diario Afectivo Semanal: registro de 3 momentos de la semana donde reguló bien y 1 donde le costó, con reflexión sobre qué estrategia podría haber usado.', 'Análisis de Situaciones (Termostato Emocional): dadas 5 situaciones de conflicto escolar, los estudiantes identifican la emoción, la intensidad (del 1 al 10) y la estrategia de regulación adecuada.'] },
    { nivel: 'Básica Secundaria (6°–9°)', bg: '#FBEAF0', tc: '#72243E', items: ['Protocolo personal de Desescalada: cada estudiante diseña un protocolo propio de 4 pasos para situaciones de alta carga emocional (confrontaciones, humillaciones públicas, presión de grupo).', 'Análisis de casos reales: estudio de situaciones escolares concretas donde la desregulación emocional escaló a conflictos graves. Identificación de los puntos de quiebre y las estrategias que podrían haber interrumpido la escalada.', 'Dramatización reflexiva: representación de escenas de desbordamiento emocional con "pausa dramática" donde el grupo propone estrategias de regulación alternativas en tiempo real.'] },
    { nivel: 'Media (10°–11°)', bg: '#FAECE7', tc: '#712B13', items: ['Investigación aplicada: diseño e implementación de un protocolo de apoyo entre pares para situaciones de crisis emocional leve (ansiedad por exámenes, rupturas relacionales, presión vocacional).', 'Análisis filosófico: "¿Es posible actuar éticamente sin regular las emociones primero? Revisión de Nussbaum (2001) y Solomon (2007) sobre emoción y decisión moral."', 'Proyecto de bienestar: creación de un recurso audiovisual o digital (guía, podcast, video) sobre estrategias de regulación emocional para adolescentes, basado en evidencia científica.'] }
  ],
  rubrica: [
    { criterio: 'Identificación de detonantes y señales', d: ['No reconoce qué situaciones o estímulos generan sus estados emocionales intensos.', 'Identifica algunos detonantes externos obvios pero no las señales corporales que los acompañan.', 'Identifica detonantes, señales corporales y pensamientos asociados a sus emociones con claridad.', 'Realiza un análisis preventivo de sus detonantes habituales y activa estrategias anticipadas antes de ser desbordado.'] },
    { criterio: 'Uso de estrategias de regulación', d: ['Reacciona de forma impulsiva o se bloquea ante las emociones intensas, sin estrategias conscientes.', 'Aplica alguna estrategia básica (respirar, alejarse) con apoyo o sugerencia externa.', 'Activa de forma autónoma estrategias variadas y adaptadas a distintas situaciones y niveles de intensidad emocional.', 'Diseña y enseña estrategias de regulación emocional a otros, mostrando alta flexibilidad y eficacia en contextos de alta exigencia.'] },
    { criterio: 'Coherencia entre emoción y valores', d: ['Actúa desde el impulso emocional sin considerar sus valores o el impacto en los demás.', 'Reconoce a posteriori cuándo actuó en contradicción con sus valores, pero no logra evitarlo en el momento.', 'Logra, con frecuencia, pausar entre la emoción y la acción para elegir una respuesta coherente con sus valores.', 'Actúa consistentemente desde sus valores incluso en estados emocionales de alta intensidad, y ayuda a otros a hacer lo mismo.'] }
  ],
  guia: {
    prop: 'Desarrollar en los docentes la capacidad de gestionar sus propias emociones en el aula de forma ética y adaptativa, construyendo estrategias concretas que puedan modelar y transferir a sus estudiantes.',
    adv: [
      'No confunda regulación con supresión: el objetivo no es que los docentes o estudiantes escondan lo que sienten, sino que actúen desde sus valores a pesar de ello.',
      'Evite universalizar estrategias de regulación: lo que funciona para unos no funciona para otros. La diversidad de estrategias es una fortaleza.',
      'Sea extremadamente cuidadoso con estudiantes que hayan vivido trauma: algunas técnicas de conciencia corporal pueden ser contraproducentes. Consulte con orientación escolar.',
      'El docente que modela la regulación emocional en público (reconocer en voz alta que está molesto y que va a tomarse un momento) tiene más impacto que cualquier técnica explicada.'
    ],
    mat: ['Botellas de la calma (o materiales para construirlas)', 'Tarjetas de estrategias de regulación', 'Termómetro de intensidad emocional (grande, para pared)', 'Fichas de registro de compromisos personales'],
    cierre: 'Cierre con la dinámica del "Compromiso Público": cada participante anuncia una estrategia específica que implementará con sus estudiantes la siguiente semana, con fecha y contexto concreto. Los compromisos quedan registrados para seguimiento.'
  }
},

/* ─────────────────────────────────────────
   CSE-3 · Toma de decisiones responsables y éticas
───────────────────────────────────────── */
{
  id: 'cse3',
  num: 'CSE-3',
  color: '#1A4FA0',
  bg: '#E6F1FB',
  tc: '#0C447C',
  icon: 'ti-scale',
  title: 'Toma de decisiones éticas',
  eje: 'Yo conmigo mismo',
  def: 'Capacidad de realizar elecciones informadas, deliberadas y coherentes con valores que promueven el bienestar propio y el de las demás personas, evaluando riesgos, anticipando consecuencias y reflexionando críticamente sobre los efectos de las propias decisiones.',
  secuencia: [
    { fase: 'Apertura (El dilema del pasillo)', tiempo: '15 min', desc: 'Se presenta un dilema escolar real: "Ves a un estudiante de otro curso siendo humillado por un grupo. El líder del grupo es el hijo del rector. Tienes 30 segundos para decidir qué haces." Cada participante escribe su decisión y la cadena de valores que la sustenta — sin consultar con nadie.', rol: 'El facilitador recoge las respuestas de forma anónima y las lee en voz alta sin juzgarlas. Muestra la diversidad de decisiones como punto de partida para la exploración.' },
    { fase: 'Exploración conceptual', tiempo: '20 min', desc: 'Presentación del modelo de toma de decisiones éticas: (1) ¿Cuál es el problema? (2) ¿Qué valores están en juego? (3) ¿Qué opciones tengo? (4) ¿Qué consecuencias tiene cada opción para mí y para los otros? (5) ¿Qué haría alguien de integridad plena? Conexión con Haidt (2001): cómo las intuiciones emocionales influyen (a veces distorsionan) la deliberación racional.', rol: 'Docente presenta el modelo con honestidad sobre sus propias limitaciones éticas reales. No como experto que ya resuelve dilemas perfectamente, sino como persona que trabaja permanentemente su coherencia.' },
    { fase: 'Práctica activa (Análisis de Casos Escolares)', tiempo: '25 min', desc: 'En grupos de 4, cada grupo analiza un caso escolar real (conflicto de notas, exclusión de un estudiante con discapacidad, presión de colega para hacer trampa en un informe). Aplican el modelo de 5 pasos y exponen su deliberación al grupo grande, argumentando la decisión desde valores explícitos.', rol: 'Facilita el debate posterior. Pregunta: ¿Cuándo la intuición emocional y el análisis racional llegaron a conclusiones distintas? ¿Cuál pesó más y por qué?' },
    { fase: 'Transferencia pedagógica', tiempo: '20 min', desc: 'Grupos por niveles diseñan una actividad de dilema ético adaptada a sus estudiantes: para inicial (elección guiada simple con consecuencias visibles), para primaria (análisis de cuento con decisión moral), para secundaria (debate sobre caso real), para media (investigación de dilema ético contemporáneo).', rol: 'Acompaña el diseño. Recuerda que el objetivo no es que el estudiante llegue a la "respuesta correcta" sino que aprenda a deliberar articulando emoción, razón y valores.' },
    { fase: 'Cierre y metacognición', tiempo: '10 min', desc: 'Retorno al dilema del pasillo del inicio: ¿Cambiaría ahora tu decisión después del recorrido de la sesión? ¿Por qué sí o no? Cierre con reflexión escrita individual.', rol: 'Recoge los textos como insumo para el diario pedagógico del grupo. No se leen en voz alta — son reflexiones privadas.' }
  ],
  actividades: [
    { nivel: 'Educación Inicial (0–5 años)', bg: '#E1F5EE', tc: '#085041', items: ['Elección con Consecuencias Visibles: el niño elige entre dos opciones simples (compartir el juguete o no) y luego observa y narra qué pasó con su compañero. El adulto facilita la reflexión: "¿Cómo se sintió él? ¿Cómo te sentiste tú?"', 'Cuentos con Dilemas: lectura de historias donde el personaje enfrenta una elección difícil. Los niños proponen qué debería hacer el personaje y por qué.', 'Asamblea de Acuerdos: los niños participan en la construcción de una norma del salón, discutiendo por qué esa norma existe y qué pasa cuando no se respeta.'] },
    { nivel: 'Básica Primaria (1°–5°)', bg: '#E6F1FB', tc: '#0C447C', items: ['El Árbol de la Decisión: herramienta gráfica donde el estudiante dibuja la decisión (tronco), las opciones (ramas) y las posibles consecuencias para sí mismo y para los demás (hojas y frutos).', 'Análisis de Situaciones Escolares: fichas con situaciones reales (encontrar dinero ajeno, ver a un amigo hacer trampa) donde el estudiante identifica el dilema, las opciones y la decisión fundamentada.', 'El Consejo de Sabios: dinámica donde los estudiantes se preguntan "¿qué haría la persona que más admiro en esta situación?" y justifican su respuesta.'] },
    { nivel: 'Básica Secundaria (6°–9°)', bg: '#FBEAF0', tc: '#72243E', items: ['Debates de Casos Reales Escolares: análisis grupal de situaciones concretas de la institución (acoso, exclusión, trampa académica) con el modelo de deliberación ética de 5 pasos.', 'Ensayo Reflexivo: "Una decisión difícil que tomé y cómo pesé las consecuencias para los demás antes de actuar."', 'Proyecto de Normas Vivas: revisión participativa del manual de convivencia — ¿cuáles normas son éticas y cuáles son solo reglamento? ¿qué cambiarían y por qué?'] },
    { nivel: 'Media (10°–11°)', bg: '#FAECE7', tc: '#712B13', items: ['Investigación de Dilemas Contemporáneos: análisis de un dilema ético actual (desinformación digital, consumo y medio ambiente, objeción de conciencia) con marco teórico explícito (Rest, 1986; Nussbaum, 2010).', 'Veeduría Estudiantil: monitoreo crítico de una decisión institucional real desde una perspectiva ética. Los estudiantes presentan sus hallazgos ante el consejo directivo.', 'Simulación de Consulta Pública: diseño y facilitación de un espacio de deliberación democrática sobre un problema real de la institución o el territorio.'] }
  ],
  rubrica: [
    { criterio: 'Reconocimiento del dilema ético', d: ['No identifica la dimensión ética en las situaciones de decisión — las aborda como problemas técnicos o normativos.', 'Identifica que hay un dilema ético cuando se le señala explícitamente, pero no lo detecta de forma autónoma.', 'Reconoce de forma autónoma la dimensión ética en situaciones cotidianas y complejas, nombrando los valores en tensión.', 'Analiza dilemas éticos con profundidad filosófica, identificando las perspectivas en juego y los marcos de valor que las sustentan.'] },
    { criterio: 'Deliberación y análisis de consecuencias', d: ['Decide de forma impulsiva o por convención, sin deliberación consciente ni análisis de consecuencias.', 'Considera algunas consecuencias inmediatas para sí mismo, pero no para los demás.', 'Evalúa consecuencias para sí mismo y para los otros, considerando el corto y mediano plazo antes de decidir.', 'Realiza una deliberación sistemática que integra análisis de riesgos, consecuencias, valores y perspectivas múltiples, incluyendo las de los grupos más vulnerables.'] },
    { criterio: 'Coherencia entre valores y acción', d: ['Actúa en contradicción con los valores que declara, sin notar la inconsistencia.', 'Reconoce la brecha entre sus valores declarados y sus decisiones reales, pero tiene dificultad para cerrarla.', 'Actúa con frecuencia en coherencia con sus valores, incluso cuando esto implica un costo personal.', 'Actúa consistentemente desde sus valores más profundos, incluso en situaciones de alta presión o riesgo personal, y puede explicar su razonamiento ético con claridad.'] }
  ],
  guia: {
    prop: 'Fortalecer en los docentes la capacidad de deliberación ética y de diseño de situaciones de aprendizaje donde sus estudiantes puedan ejercitar la toma de decisiones responsables ante dilemas reales de su contexto.',
    adv: [
      'No presente los dilemas éticos como si tuvieran una única "respuesta correcta" — el objetivo es la deliberación de calidad, no la respuesta esperada.',
      'Evite dilemas que impliquen la exposición de situaciones personales traumáticas de los participantes. Use situaciones escolares ficticias pero verosímiles.',
      'Reconozca que en algunos contextos colombianos (zonas de conflicto, comunidades con alta presión de grupos armados) ciertos dilemas éticos tienen consecuencias físicas reales. Ajuste la profundidad del trabajo con sensibilidad.',
      'El docente debe ser capaz de modelar la deliberación ética en voz alta: "Yo en esta situación siento que... pero mis valores me dicen que... por eso decido..."'
    ],
    mat: ['Fichas de casos escolares con dilemas éticos', 'Árbol de decisiones (plantilla grande para pared)', 'Tarjetas de valores para deliberación grupal', 'Rúbrica de deliberación ética para autoevaluación'],
    cierre: 'Cierre con el "Compromiso de Coherencia": cada participante identifica una situación de su práctica actual donde sus decisiones no están siendo coherentes con sus valores y escribe una acción concreta de ajuste. Es privado y no se comparte en grupo.'
  }
},

/* ─────────────────────────────────────────
   CSE-4 · Empatía y reconocimiento del otro
───────────────────────────────────────── */
{
  id: 'cse4',
  num: 'CSE-4',
  color: '#0C7A4A',
  bg: '#E1F5EE',
  tc: '#064D2F',
  icon: 'ti-heart-handshake',
  title: 'Empatía y reconocimiento del otro',
  eje: 'Yo con los otros',
  def: 'Capacidad de adoptar la perspectiva de otras personas, comprender sus sentimientos, reconocer su dignidad inherente y valorar la diferencia como parte constitutiva de la vida social. Integra el descentramiento cognitivo, la resonancia emocional y la comunicación empática.',
  secuencia: [
    { fase: 'Apertura (La Historia de los Tres Pares de Zapatos)', tiempo: '15 min', desc: 'Cada participante escribe en un papel el nombre de un estudiante que le resulta "difícil" y describe brevemente por qué. Luego se les pide que piensen: ¿qué historia de vida podría explicar ese comportamiento? ¿qué miedo, herida o necesidad podría haber detrás? No se comparten los nombres — es un ejercicio interno de descentramiento.', rol: 'El facilitador abre compartiendo su propio ejemplo de un estudiante que inicialmente le resultó difícil y cómo conocer más de su historia transformó la relación.' },
    { fase: 'Exploración conceptual', tiempo: '20 min', desc: 'Diferenciación entre empatía cognitiva (comprender intelectualmente la perspectiva del otro), empatía afectiva (resonar emocionalmente con lo que el otro siente) y comunicación empática (expresar esa comprensión de forma que el otro se sienta reconocido). Análisis del riesgo de la sobreidentificación empática: cuándo la empatía paraliza en lugar de movilizar.', rol: 'Docente usa ejemplos de la convivencia escolar real: el estudiante que llora en clase, el padre que grita en reunión, el colega que se queja permanentemente. ¿Cuándo empatizamos y cuándo nos desconectamos? ¿Por qué?' },
    { fase: 'Práctica activa (Círculo de Perspectivas)', tiempo: '25 min', desc: 'Se presenta una situación escolar de conflicto desde la perspectiva de 4 actores (estudiante, docente, familia, directivo). Grupos de 4 toman cada perspectiva y la defienden con empatía genuina. Luego rotan. Al final, el grupo identifica qué elementos de la situación solo se comprenden adoptando la perspectiva del otro.', rol: 'Facilita la rotación de roles y la reflexión posterior. Pregunta clave: "¿Qué perspectiva les costó más habitar? ¿Por qué?"' },
    { fase: 'Transferencia pedagógica', tiempo: '20 min', desc: 'Grupos por niveles co-diseñan una actividad de descentramiento empático para sus estudiantes. Para inicial: juego de espejo o cuento sobre diversidad. Para primaria: círculo de diálogo sobre injusticia. Para secundaria: análisis de relatos de vida. Para media: proyecto de encuentro con comunidades diversas.', rol: 'Acompaña el diseño. Recuerda que la empatía se desarrolla en encuentros reales con la diferencia — no en discursos sobre tolerancia.' },
    { fase: 'Cierre y metacognición', tiempo: '10 min', desc: 'Retorno al estudiante "difícil" del inicio: ¿cambió algo en su perspectiva sobre ese estudiante después del recorrido de la sesión? ¿Qué haría diferente en el próximo encuentro con él o ella?', rol: 'Recoge las reflexiones con cuidado. Cierra con una cita de Nussbaum: "La empatía no es debilidad — es el fundamento de toda decisión ética justa."' }
  ],
  actividades: [
    { nivel: 'Educación Inicial (0–5 años)', bg: '#E1F5EE', tc: '#085041', items: ['Cuentos sobre Diversidad: lectura dialógica de libros que representen familias, cuerpos, culturas y formas de vida diversas. Los niños identifican similitudes y diferencias con curiosidad y respeto.', 'El Rincón del Cuidado: espacio donde un niño "cuida" a otro (le presta un material, le ayuda con un zapato, le da un abrazo si está triste). El adulto nombra la acción como empatía.', 'Juego de Roles Simples: "Hoy tú eres el maestro y yo soy el estudiante. ¿Cómo te sientes cuando alguien no escucha?" Intercambio de perspectivas en situaciones de juego cotidiano.'] },
    { nivel: 'Básica Primaria (1°–5°)', bg: '#E6F1FB', tc: '#0C447C', items: ['Círculos de Diálogo sobre Injusticia: a partir de una situación escolar donde alguien fue excluido, el grupo habla de cómo se sintió esa persona y qué podría hacerse diferente.', 'Análisis de Relatos de Vida: lectura de testimonios sencillos de niños de otros contextos (migrantes, con discapacidad, de comunidades indígenas) seguido de preguntas empáticas.', 'La Carta desde el Otro Lado: cada estudiante escribe una carta en la voz de un personaje de un conflicto escolar real, explicando cómo se siente y qué necesita.'] },
    { nivel: 'Básica Secundaria (6°–9°)', bg: '#FBEAF0', tc: '#72243E', items: ['Análisis de Testimonios de Memoria: lectura de relatos de personas víctimas del conflicto armado colombiano o de discriminación. Identificación de las emociones, los valores vulnerados y las necesidades expresadas.', 'Campañas contra la Discriminación: diseño y ejecución de campañas estudiantiles que visibilicen situaciones de exclusión real en la institución con propuestas concretas de cambio.', 'Proyecto de Encuentro Intercultural: visita, entrevista o conversación con personas de comunidades diversas (étnicas, generacionales, en condición de discapacidad) dentro o fuera de la institución.'] },
    { nivel: 'Media (10°–11°)', bg: '#FAECE7', tc: '#712B13', items: ['Ensayo filosófico: "La empatía como fundamento de la justicia: entre Hoffman (2000), Nussbaum (2010) y las prácticas de reconciliación en Colombia."', 'Investigación de Campo: mapeo de las barreras de empatía institucional (¿con qué grupos o personas es más difícil empatizar en esta institución y por qué?) con propuestas de intervención pedagógica.', 'Producción narrativa: creación de una historia corta, crónica o pieza audiovisual que transmita la perspectiva de un actor invisibilizado en la comunidad educativa.'] }
  ],
  rubrica: [
    { criterio: 'Descentramiento cognitivo', d: ['Interpreta todas las situaciones exclusivamente desde su propia perspectiva, sin considerar otros puntos de vista.', 'Puede nombrar la perspectiva de otro cuando se le solicita explícitamente, pero no lo hace de forma espontánea.', 'Adopta de forma autónoma la perspectiva de otros en situaciones de conflicto o diversidad, comprendiendo sus razones y sentimientos.', 'Analiza situaciones complejas desde múltiples perspectivas simultáneas, incluyendo las de grupos históricamente marginados, con profundidad y rigor.'] },
    { criterio: 'Resonancia emocional y comunicación empática', d: ['No muestra señales de resonancia emocional con las experiencias de otros; responde con indiferencia o invalidación.', 'Reconoce el estado emocional del otro pero tiene dificultad para comunicar comprensión de manera que el otro se sienta reconocido.', 'Expresa comprensión empática de manera auténtica, validando los sentimientos del otro sin necesariamente estar de acuerdo con sus acciones.', 'Practica una comunicación empática profunda que genera confianza y abre posibilidades de diálogo incluso en contextos de alta tensión relacional.'] },
    { criterio: 'Reconocimiento de la dignidad del otro', d: ['Utiliza lenguaje o actitudes que desvalorizan a personas diferentes (burlas, estereotipos, exclusión pasiva).', 'Evita conductas explícitas de discriminación pero no toma acciones activas de reconocimiento de la dignidad de los demás.', 'Reconoce activamente la dignidad de personas diversas y señala situaciones de irrespeto cuando las observa.', 'Promueve activamente culturas relacionales basadas en el reconocimiento de la dignidad humana en todos los espacios donde participa.'] }
  ],
  guia: {
    prop: 'Desarrollar en los docentes la capacidad de adoptar la perspectiva de sus estudiantes, familias y colegas como fundamento de su práctica pedagógica, y transferir esta competencia a través de experiencias de encuentro genuino con la diferencia.',
    adv: [
      'Diferencie claramente empatía de lástima: la empatía reconoce al otro como igual con una experiencia diferente; la lástima lo sitúa en posición de inferioridad.',
      'Cuide la sobreidentificación empática: si el docente se fusiona emocionalmente con el dolor de sus estudiantes, pierde la capacidad de acompañar con ecuanimidad. La empatía saludable mantiene diferenciación.',
      'En contextos de posconflicto o con estudiantes que han sufrido violencia, la empatía pedagógica requiere acompañamiento de profesionales de la salud mental. No intente hacer terapia en el aula.',
      'Evite los "ejercicios de empatía forzada" donde se obliga a los participantes a simular situaciones de sufrimiento ajeno. Pueden ser retraumatizantes para personas que han vivido experiencias similares.'
    ],
    mat: ['Tarjetas de perspectivas para el Círculo de Perspectivas', 'Selección de relatos de vida de distintos contextos colombianos', 'Cuentos y libros con personajes de diversidad cultural, étnica y de capacidades', 'Plantilla de "La Carta desde el Otro Lado"'],
    cierre: 'Cierre con la dinámica de "El Gesto de Reconocimiento": cada participante elige una persona del grupo cuya perspectiva le resultó reveladora durante la sesión y le expresa (verbalmente o por escrito) qué aprendió de ver las cosas a través de sus ojos.'
  }
},

/* ─────────────────────────────────────────
   CSE-5 · Habilidades de relación y resolución pacífica de conflictos
───────────────────────────────────────── */
{
  id: 'cse5',
  num: 'CSE-5',
  color: '#72243E',
  bg: '#FBEAF0',
  tc: '#4A1329',
  icon: 'ti-messages',
  title: 'Habilidades de relación y resolución de conflictos',
  eje: 'Yo con los otros',
  def: 'Capacidad de establecer, mantener y transformar relaciones interpersonales de manera constructiva, respetuosa y cooperativa, comprendiendo el conflicto como oportunidad de aprendizaje y construyendo soluciones basadas en el diálogo, la escucha activa y la cooperación.',
  secuencia: [
    { fase: 'Apertura (Inventario de conflictos)', tiempo: '15 min', desc: 'Cada participante escribe en silencio un conflicto relacional actual en su vida profesional (con un colega, un estudiante, un directivo o una familia). No de un conflicto pasado y resuelto — uno presente y vivo. Luego identifica: ¿qué comunicación ha ocurrido? ¿qué comunicación ha evitado? ¿qué teme que pase si aborda el conflicto directamente?', rol: 'El facilitador normaliza la existencia del conflicto como dato de la vida relacional, no como señal de fracaso. Comparte brevemente su propio conflicto actual.' },
    { fase: 'Exploración conceptual', tiempo: '20 min', desc: 'Diferenciación entre comunicación efectiva (expresar con claridad y asertividad) y comunicación empática (escuchar activamente y validar). Modelo de resolución cooperativa de conflictos: (1) Describir el comportamiento observado sin evaluar. (2) Expresar el impacto emocional en primera persona. (3) Identificar la necesidad subyacente. (4) Formular una petición concreta y posible. Presentación de Galtung (1996): la diferencia entre violencia directa, estructural y cultural en los conflictos escolares.', rol: 'Docente presenta con ejemplos concretos del aula. Destaca: la mayoría de los conflictos escolares no escalan por los hechos en sí, sino por cómo se comunican.' },
    { fase: 'Práctica activa (El Laboratorio de Conversaciones)', tiempo: '25 min', desc: 'En parejas, cada participante practica la conversación que ha estado evitando con el conflicto real del inicio (adaptado, sin nombres). Un participante habla usando el modelo de 4 pasos; el otro escucha activamente y replica. Luego invierten roles. Un tercer observador evalúa con una rúbrica simple de comunicación efectiva.', rol: 'Circula por los grupos dando retroalimentación en tiempo real. Interviene solo cuando el modelo de comunicación se rompe de forma que afecta la seguridad psicológica del ejercicio.' },
    { fase: 'Transferencia pedagógica', tiempo: '20 min', desc: 'Grupos por niveles diseñan un protocolo de mediación entre pares adaptado a su contexto educativo. Incluye: roles (mediador, partes), pasos del proceso, criterios de acuerdo y seguimiento. El protocolo debe ser realista y usable por los propios estudiantes.', rol: 'Acompaña el diseño. Pregunta: ¿qué condiciones institucionales necesita este protocolo para funcionar realmente? ¿Quién lo respalda? ¿Cómo se forma a los mediadores?' },
    { fase: 'Cierre y metacognición', tiempo: '10 min', desc: 'Retorno al conflicto del inicio: ¿qué primer paso podrías dar esta semana para abordar ese conflicto real? ¿Qué necesitas para darlo? Cada participante escribe su compromiso en una tarjeta personal.', rol: 'Recoge las tarjetas y las devuelve selladas en la próxima sesión como recordatorio del compromiso.' }
  ],
  actividades: [
    { nivel: 'Educación Inicial (0–5 años)', bg: '#E1F5EE', tc: '#085041', items: ['Cuentos sobre Convivencia: lectura de historias donde personajes tienen desacuerdos y los resuelven mediante el diálogo y la reparación. El adulto facilita la reflexión.', 'El Turno de Hablar: uso de un objeto símbolo (concha, piedra, muñeco) que otorga el turno de hablar. Solo habla quien lo tiene. Desarrolla escucha activa desde pequeño.', 'Mediación Guiada Simple: ante un conflicto entre dos niños, el adulto facilita que cada uno diga cómo se sintió y qué necesita, y propone juntos una solución que cuide a los dos.'] },
    { nivel: 'Básica Primaria (1°–5°)', bg: '#E6F1FB', tc: '#0C447C', items: ['Protocolo de los 3 Pasos: herramienta visual del aula — (1) Calma (respira), (2) Habla (di cómo te sientes), (3) Escucha (turno del otro). Los estudiantes lo usan autónomamente ante conflictos menores.', 'Asamblea Semanal de Aula: espacio quincenal donde el grupo revisa los acuerdos de convivencia, reconoce lo que funcionó y resuelve colectivamente lo que no funcionó.', 'Juego Cooperativo de Resolución: dinámicas de juego donde el grupo solo puede ganar si resuelve un problema juntos, sin que nadie tome el control unilateral.'] },
    { nivel: 'Básica Secundaria (6°–9°)', bg: '#FBEAF0', tc: '#72243E', items: ['Programa de Mediación entre Pares: formación de un grupo de estudiantes como mediadores escolares. Protocolo claro, supervisión docente y casos reales (con consentimiento).', 'Análisis de Conflictos Escolares Reales: estudio de un conflicto escolar (con datos anonimizados) desde las perspectivas de todos los actores, identificando puntos de escalada y de posible desescalada.', 'Dramatización con Pausa: representación de una situación de conflicto con la técnica del "teatro del oprimido" — el público puede detener la escena y proponer acciones alternativas en tiempo real.'] },
    { nivel: 'Media (10°–11°)', bg: '#FAECE7', tc: '#712B13', items: ['Círculo Restaurativo: implementación de un círculo de diálogo restaurativo ante un conflicto institucional real, con el protocolo completo (preparación, círculo, acuerdos, seguimiento).', 'Proyecto de Cultura de Paz: diseño e implementación de una iniciativa institucional que transforme una práctica de violencia simbólica o directa identificada por los propios estudiantes.', 'Análisis comparado: "¿Cómo resuelven conflictos las comunidades indígenas colombianas? Justicia propia y prácticas restaurativas en comunidades afrocolombianas e indígenas vs. modelo punitivo estatal."'] }
  ],
  rubrica: [
    { criterio: 'Comunicación efectiva y asertiva', d: ['Se expresa de forma agresiva, pasiva o evasiva ante situaciones de conflicto o tensión relacional.', 'Expresa sus puntos de vista pero sin escuchar activamente ni considerar el impacto en el otro.', 'Comunica necesidades y perspectivas de forma clara, respetuosa y asertiva, y escucha activamente al otro.', 'Modela y enseña comunicación efectiva en contextos de alta tensión, facilitando conversaciones difíciles que otros evitan.'] },
    { criterio: 'Resolución cooperativa de conflictos', d: ['Evita el conflicto, lo escala o impone su perspectiva sin considerar la del otro.', 'Intenta resolver conflictos pero sin un proceso claro; las soluciones son provisionales y no atienden las necesidades subyacentes.', 'Aplica un proceso de resolución cooperativa que identifica necesidades de ambas partes y construye acuerdos sostenibles.', 'Facilita la resolución de conflictos complejos entre terceros, construyendo acuerdos que fortalecen las relaciones y la comunidad.'] },
    { criterio: 'Comprensión del conflicto como oportunidad', d: ['Experimenta el conflicto como amenaza personal o fracaso relacional. Lo evita o lo reprime.', 'Reconoce conceptualmente que el conflicto puede ser productivo, pero en la práctica tiende a evitarlo o resolverlo rápidamente sin aprovecharlo pedagógicamente.', 'Utiliza los conflictos del aula o la institución como oportunidades de aprendizaje sobre convivencia, valores y relaciones.', 'Diseña intencionalmente situaciones que generan disonancia cognitiva y emocional productiva, convirtiendo el conflicto en motor de aprendizaje ciudadano.'] }
  ],
  guia: {
    prop: 'Desarrollar en los docentes la capacidad de comunicarse de forma efectiva y asertiva ante situaciones de tensión, y transferir a sus estudiantes herramientas concretas de mediación y resolución cooperativa de conflictos.',
    adv: [
      'Los protocolos de mediación escolar requieren respaldo institucional claro. Un docente que los implementa solo, sin apoyo directivo, queda en una posición de alta vulnerabilidad.',
      'Diferencie entre conflictos que pueden y deben resolverse pedagógicamente (desacuerdos de convivencia, diferencias de opinión) y situaciones que requieren intervención institucional o profesional (acoso sostenido, violencia física, situaciones de riesgo).',
      'La escucha activa genuina es una de las habilidades más escasas en los entornos escolares colombianos. Dé tiempo suficiente a su práctica — no basta con explicarla.',
      'Los mediadores entre pares necesitan supervisión continua. Sin acompañamiento, pueden reproducir dinámicas de poder existentes en lugar de transformarlas.'
    ],
    mat: ['Tarjetas con el modelo de comunicación de 4 pasos', 'Rúbrica de observación para el Laboratorio de Conversaciones', 'Protocolo de mediación escolar (adaptable por nivel)', 'Objeto símbolo para el turno de hablar'],
    cierre: 'Cierre con el "Acuerdo de Convivencia del Grupo": el propio grupo de docentes co-construye 3-5 acuerdos de convivencia para sus espacios compartidos (sala de profesores, reuniones de área, WhatsApp docente). El proceso de construcción es tan formativo como el resultado.'
  }
},

/* ─────────────────────────────────────────
   CSE-6 · Transformación de emociones políticas en acción ciudadana
───────────────────────────────────────── */
{
  id: 'cse6',
  num: 'CSE-6',
  color: '#B35900',
  bg: '#FFF3E0',
  tc: '#6D3800',
  icon: 'ti-speakerphone',
  title: 'Emociones políticas y acción ciudadana',
  eje: 'Yo con la sociedad',
  def: 'Capacidad para reconocer emociones colectivas — como la indignación, la ira moral, la frustración o la esperanza compartida — y canalizarlas de manera constructiva hacia la búsqueda de justicia, la defensa de la dignidad humana y la participación democrática. No suprimir las emociones sino comprender su potencia política y orientarlas hacia el bien común.',
  secuencia: [
    { fase: 'Apertura (Mapa de Indignación)', tiempo: '15 min', desc: 'Cada participante responde en silencio: ¿Qué situación de injusticia en tu institución, comunidad o país te genera más indignación hoy? ¿Qué emoción sientes cuando piensas en esa situación? ¿Qué has hecho con esa emoción hasta ahora: la has suprimido, la has expresado, la has convertido en alguna acción? Se comparte en parejas antes de abrirse al grupo.', rol: 'El facilitador normaliza la indignación como respuesta ética legítima, no como "falta de profesionalismo". Cita a Nussbaum (2014): las emociones políticas son expresiones evaluativas de lo que consideramos valioso para la vida justa.' },
    { fase: 'Exploración conceptual', tiempo: '20 min', desc: 'Diferenciación entre emoción política individual (lo que yo siento frente a una injusticia) y emoción política colectiva (lo que un grupo comparte y que puede movilizarlo o paralizarlo). Análisis de cómo las emociones "viajan" entre personas y discursos (Ahmed, 2004). Diferenciación entre indignación constructiva (que genera propuesta y acción) e indignación destructiva (que genera violencia, resentimiento o apatía). El papel de la esperanza como fuerza política activa (Freire).', rol: 'Docente conecta con situaciones históricas colombianas concretas: ¿qué emociones colectivas han movido procesos de cambio social en Colombia? ¿Y cuáles han sustentado ciclos de violencia?' },
    { fase: 'Práctica activa (Del malestar a la propuesta)', tiempo: '25 min', desc: 'Grupos de 5 toman la situación de injusticia más compartida del grupo (identificada en la apertura). Completan el ciclo: (1) Nombrar la emoción colectiva con precisión. (2) Identificar la injusticia estructural que la genera. (3) Analizar qué se ha hecho hasta ahora y por qué no ha sido suficiente. (4) Proponer una acción ciudadana concreta, realizable y medible dentro del ámbito escolar o comunitario.', rol: 'Facilita que los grupos distingan entre propuestas de acción real (que ellos pueden ejecutar) y demandas al sistema (que requieren otros actores). Ambas son válidas, pero tienen lógicas distintas.' },
    { fase: 'Transferencia pedagógica', tiempo: '20 min', desc: 'Grupos por niveles diseñan cómo trabajar las emociones políticas con sus estudiantes: para inicial (reconocer injusticia simple y proponer norma de cuidado), para primaria (análisis de noticias locales y propuesta de acción escolar), para secundaria (gobierno escolar como espacio de transformación real), para media (liderazgo estudiantil en problemáticas del territorio).', rol: 'Acompaña el diseño. Recuerda que trabajar emociones políticas en el aula requiere que el docente primero las haya procesado en sí mismo — no se puede enseñar a transformar la indignación si se la suprime.' },
    { fase: 'Cierre y metacognición', tiempo: '10 min', desc: 'Retorno al mapa de indignación del inicio: ¿Qué primer paso de acción ciudadana tomarás a partir de esa indignación? ¿Solo o en colectivo? ¿Cuándo? Cierre con la frase de Freire: "La esperanza no es un lujo — es una necesidad ontológica del ser humano."', rol: 'Recoge los compromisos. Cierra el espacio con un gesto simbólico de reconocimiento colectivo.' }
  ],
  actividades: [
    { nivel: 'Educación Inicial (0–5 años)', bg: '#E1F5EE', tc: '#085041', items: ['Reconocer la injusticia cotidiana: ante situaciones de "no es justo" en el juego, el adulto no minimiza — valida la emoción y pregunta "¿qué podríamos hacer para que sea justo para todos?"', 'Microacciones de cuidado colectivo: proyectos de cuidado de plantas, animales o espacios del colegio que enseñan que las acciones individuales tienen efectos colectivos.', 'Cuentos de justicia y solidaridad: selección de libros donde los personajes enfrentan injusticias y actúan colectivamente para resolverlas (no el héroe solitario, sino el grupo que se organiza).'] },
    { nivel: 'Básica Primaria (1°–5°)', bg: '#E6F1FB', tc: '#0C447C', items: ['Análisis de Noticias Locales: lectura comentada de una noticia sobre un problema del territorio con preguntas: ¿Qué sientes cuando lees esto? ¿Qué crees que está mal? ¿Qué podrían hacer los estudiantes de este colegio al respecto?', 'Proyecto de Acción Escolar: identificación de un problema real del colegio (basura, exclusión de un grupo, norma injusta) y diseño colectivo de una propuesta de cambio.', 'Gobierno Escolar como Aprendizaje Real: participación genuina en los mecanismos de representación estudiantil, con seguimiento docente de los procesos y los resultados.'] },
    { nivel: 'Básica Secundaria (6°–9°)', bg: '#FBEAF0', tc: '#72243E', items: ['Análisis crítico de emociones en redes sociales: estudio de cómo circula la indignación colectiva en redes (hashtags, campañas) y cuáles generan cambio real vs. cuáles generan solo catarsis digital.', 'Cabildos Estudiantiles: espacios de deliberación formal donde los estudiantes presentan problemáticas del territorio y construyen propuestas con argumentación estructurada.', 'Veeduría Escolar: monitoreo estudiantil de una decisión institucional (uso de recursos, cumplimiento de normas) con presentación de hallazgos ante directivos.'] },
    { nivel: 'Media (10°–11°)', bg: '#FAECE7', tc: '#712B13', items: ['Marco teórico aplicado: análisis de "Emociones políticas" de Nussbaum (2014) y su aplicación a un proceso de movilización social colombiano reciente.', 'Proyecto de Incidencia Comunitaria: formulación y ejecución de una iniciativa que conecte un problema real del territorio con una propuesta de solución liderada por los estudiantes.', 'Análisis de movimientos sociales colombianos: estudio de las emociones colectivas que han sustentado movimientos como el Paro Nacional, las movilizaciones estudiantiles o los procesos de paz, identificando su estructura emocional y su estrategia de acción.'] }
  ],
  rubrica: [
    { criterio: 'Reconocimiento de emociones colectivas', d: ['No identifica ni nombra las emociones que circulan en su entorno social y político. Las suprime o las niega.', 'Reconoce emociones colectivas evidentes (euforia en eventos, malestar ante injusticias obvias) pero no analiza su origen ni su dinámica.', 'Identifica y nombra con precisión las emociones colectivas de su entorno, comprende cómo se generan y cómo circulan entre personas y grupos.', 'Analiza críticamente cómo las emociones políticas configuran identidades colectivas, movilizan o paralizan la acción, y pueden ser educadas hacia la justicia o instrumentalizadas para la exclusión.'] },
    { criterio: 'Canalización hacia la acción ciudadana', d: ['Las emociones políticas se quedan en queja o resentimiento. No hay conversión en propuesta ni en acción.', 'Propone acciones individuales ante injusticias pero no las articula con acciones colectivas ni con procesos democráticos existentes.', 'Transforma la indignación o la esperanza en propuestas concretas de acción ciudadana, articuladas con otros y con los mecanismos de participación disponibles.', 'Lidera procesos de transformación social desde las emociones políticas, movilizando a su comunidad hacia acciones colectivas fundamentadas en valores de justicia y dignidad.'] },
    { criterio: 'Esperanza activa y sostenida', d: ['Prevalece una postura de fatalismo, resignación o desesperanza frente a los problemas sociales e institucionales.', 'Expresa esperanza de forma verbal pero no la traduce en acciones sostenidas en el tiempo.', 'Mantiene una disposición activa hacia el cambio posible, sustentada en análisis crítico y en iniciativas concretas.', 'Cultiva y transmite esperanza política fundamentada en otros, contribuyendo a crear culturas institucionales y comunitarias orientadas a la transformación justa y sostenida.'] }
  ],
  guia: {
    prop: 'Desarrollar en los docentes la capacidad de reconocer, nombrar y canalizar las emociones políticas propias y de sus comunidades hacia la participación democrática y la transformación social, modelando el paso del malestar a la propuesta.',
    adv: [
      'Las emociones políticas son terreno sensible en Colombia. Tenga claridad sobre el contexto institucional antes de profundizar en temas de indignación política — algunos contextos implican riesgos reales para docentes o estudiantes.',
      'Diferencie entre educar emocionalmente para la democracia (legítimo y obligatorio) y promover posturas políticas partidistas (inapropiado en el espacio educativo).',
      'La esperanza pedagógica no debe volverse ingenuidad — la indignación ante la injusticia real es una respuesta ética correcta. No la apague: canalícela.',
      'Cuide especialmente a los estudiantes que han vivido directamente la violencia política, el desplazamiento o la pérdida de familiares. Para ellos, ciertos ejercicios requieren acompañamiento psicosocial específico.'
    ],
    mat: ['Selección de noticias de medios regionales (no solo nacionales) sobre problemas del territorio', 'Mapas del territorio para identificar problemáticas locales', 'Fichas del ciclo "del malestar a la propuesta"', 'Selección de testimonios de líderes sociales locales'],
    cierre: 'Cierre con la construcción colectiva de un "Mural de la Esperanza Activa": cada grupo escribe una injusticia que identifica y, junto a ella, una acción ciudadana concreta que podría transformarla. El mural queda visible en el espacio como recordatorio de que la esperanza política no es pasiva — es un compromiso de acción.'
  }
},

/* ─────────────────────────────────────────
   CSE-7 · Resiliencia comunitaria orientada a la paz
───────────────────────────────────────── */
{
  id: 'cse7',
  num: 'CSE-7',
  color: '#5A2E8A',
  bg: '#F0EBFB',
  tc: '#3A1B5E',
  icon: 'ti-seedling',
  title: 'Resiliencia comunitaria y paz',
  eje: 'Yo con la sociedad',
  def: 'Capacidad colectiva para afrontar y superar adversidades, mantener la esperanza, reconstruir la confianza y tejer relaciones constructivas incluso después de experiencias de violencia, exclusión o conflicto. La resiliencia no es un rasgo individual — es una fuerza que se produce en las relaciones, las prácticas culturales y los proyectos compartidos.',
  secuencia: [
    { fase: 'Apertura (La historia de la escuela herida)', tiempo: '15 min', desc: 'Se invita a los participantes a pensar en una adversidad que ha vivido su institución o comunidad educativa como colectivo (no como personas individuales): una crisis de violencia, un período de pandemia, un conflicto institucional profundo, una tragedia que afectó a la comunidad. ¿Cómo respondió la institución como colectivo? ¿Qué la sostuvo? ¿Qué la fracturó?', rol: 'El facilitador crea un espacio de escucha profunda y no-juicio. Comparte brevemente una experiencia de resiliencia colectiva que conoce — no necesariamente personal.' },
    { fase: 'Exploración conceptual', tiempo: '20 min', desc: 'Diferenciación entre resiliencia individual (capacidad personal de sobreponerse) y resiliencia comunitaria (capacidad del colectivo de reconstruir vínculos, confianza y proyecto compartido después de la adversidad). Marco teórico: Cyrulnik (2002) — la comunidad resiliente transforma el sufrimiento en fuerza activa. Lederach (2005) — reconstrucción relacional y creatividad comunitaria. Nussbaum (2014) — la esperanza como disposición política activa, no como ilusión.', rol: 'Docente conecta con el contexto colombiano: ¿qué prácticas comunitarias, culturales o espirituales han sostenido la resiliencia en comunidades que han vivido el conflicto armado? ¿Qué puede aprender la escuela de esas prácticas?' },
    { fase: 'Práctica activa (Cartografía de la resiliencia)', tiempo: '25 min', desc: 'En grupos, los participantes mapean los recursos de resiliencia de su comunidad educativa: ¿Quiénes son las personas "ancla" que sostienen al grupo en momentos difíciles? ¿Qué prácticas, rituales o espacios generan cohesión? ¿Qué narrativas colectivas les dan sentido a la adversidad? ¿Qué recursos externos (redes, organizaciones, programas) están disponibles? El mapa se hace visible en papel grande.', rol: 'Facilita que los grupos distingan entre recursos ya existentes (que pueden fortalecer) y recursos ausentes (que pueden construir). El objetivo es ver que la resiliencia ya está — muchas veces no la hemos nombrado.' },
    { fase: 'Transferencia pedagógica', tiempo: '20 min', desc: 'Grupos por niveles diseñan una práctica pedagógica de resiliencia comunitaria: para inicial (rituale de acogida y pertenencia), para primaria (proyecto de memoria oral del barrio), para secundaria (círculo restaurativo ante una crisis grupal), para media (proyecto de construcción de paz con actores del territorio).', rol: 'Acompaña el diseño. Recuerda que la resiliencia se construye en la cotidianidad — no solo en los momentos de crisis. Las prácticas cotidianas de cuidado, reconocimiento y pertenencia son el suelo donde crece.' },
    { fase: 'Cierre y metacognición', tiempo: '10 min', desc: 'Ritual de cierre colectivo: cada participante nombra una fortaleza de la comunidad presente en la sala — no una fortaleza individual, sino algo que hace fuerte a este grupo como colectivo. Se teje una "red de resiliencia" verbal.', rol: 'Recibe cada fortaleza sin evaluarla. Cierra con la imagen de Lederach: la paz no es la ausencia de conflicto — es la calidad de las relaciones con las que una comunidad puede afrontar el conflicto sin destruirse.' }
  ],
  actividades: [
    { nivel: 'Educación Inicial (0–5 años)', bg: '#E1F5EE', tc: '#085041', items: ['Rituales de Acogida Diaria: una rutina fija y predecible de bienvenida al aula (canción, saludo, abrazo acordado) que genera la seguridad afectiva base de la resiliencia.', 'Cuentos de Personajes que Superan Dificultades Juntos: énfasis en historias donde el grupo — no el héroe individual — resuelve la adversidad mediante el cuidado mutuo.', 'Árbol de los Deseos del Grupo: mural colectivo donde los niños dibujan o pegan imágenes de lo que quieren que sea su salón o su barrio. Construye imaginario compartido de futuro posible.'] },
    { nivel: 'Básica Primaria (1°–5°)', bg: '#E6F1FB', tc: '#0C447C', items: ['Proyecto de Memoria Oral del Barrio: entrevistas a personas mayores de la comunidad sobre cómo el barrio ha superado momentos difíciles. Los niños recogen y presentan esas historias.', 'Mural del Cuidado Colectivo: construcción de un mural que represente "qué hacemos en este salón cuando alguien está mal". Establece cultura de cuidado como norma explícita.', 'Reconstrucción después del Conflicto: protocolo visible en el aula para "reparar" después de un conflicto — no solo "pedir perdón", sino acciones concretas de reparación y retorno a la convivencia.'] },
    { nivel: 'Básica Secundaria (6°–9°)', bg: '#FBEAF0', tc: '#72243E', items: ['Proyectos de Memoria Histórica Local: investigación sobre eventos difíciles de la historia del municipio o la institución, con énfasis en cómo la comunidad respondió y qué aprendió.', 'Círculos Restaurativos ante Crisis: implementación del protocolo de círculo restaurativo cuando ocurre un evento que afecta el clima del grupo (conflicto grave, pérdida, crisis institucional).', 'Red de Apoyo entre Pares: diseño de un sistema de acompañamiento estudiantil donde los estudiantes con más recursos de resiliencia acompañan a quienes están pasando por momentos difíciles.'] },
    { nivel: 'Media (10°–11°)', bg: '#FAECE7', tc: '#712B13', items: ['Análisis de prácticas de resiliencia comunitaria colombiana: estudio de comunidades que han reconstruido el tejido social después del conflicto armado — comunidades indígenas, afrocolombianas, campesinas. ¿Qué prácticas culturales han sido la base de esa resiliencia?', 'Proyecto de Construcción de Paz con Actores del Territorio: alianza con organizaciones de paz local para diseñar e implementar una iniciativa de reconciliación o reconstrucción del tejido social.', 'Marco teórico aplicado: revisión de Lederach (2005) "La imaginación moral" y su aplicación al contexto colombiano de posconflicto. Debate: ¿puede una institución educativa ser agente de reconciliación territorial?'] }
  ],
  rubrica: [
    { criterio: 'Reconocimiento de los recursos de resiliencia colectivos', d: ['No identifica los recursos de resiliencia de su comunidad educativa. Tiende a enfocar los déficits y las carencias.', 'Identifica algunos recursos cuando se le pregunta, pero no los moviliza activamente.', 'Identifica, nombra y moviliza los recursos de resiliencia de su comunidad (personas ancla, prácticas, narrativas, redes) ante situaciones de adversidad.', 'Mapea sistemáticamente los recursos de resiliencia de su contexto educativo y comunitario, y los fortalece intencionalmente como parte de su práctica pedagógica.'] },
    { criterio: 'Reconstrucción de vínculos y confianza', d: ['Ante conflictos o crisis, tiende a la ruptura de vínculos, la exclusión o el repliegue individual.', 'Intenta mantener relaciones después de conflictos, pero sin un proceso claro de reparación o reconstrucción.', 'Promueve procesos de reparación, restauración y reconstrucción de confianza después de conflictos o adversidades, con estrategias concretas.', 'Lidera procesos institucionales de reconstrucción del tejido relacional después de crisis, generando nuevos acuerdos y prácticas de convivencia más justos y sostenibles.'] },
    { criterio: 'Esperanza activa y proyecto compartido', d: ['Prevalece el fatalismo, la resignación o la sensación de que "nada puede cambiar" frente a las adversidades estructurales.', 'Mantiene esperanza personal pero no logra traducirla en proyectos colectivos o contagiarla al grupo.', 'Sostiene y transmite esperanza activa, fundada en análisis realista de la situación y en iniciativas concretas de cambio compartidas con otros.', 'Cultiva en su comunidad educativa una cultura de esperanza activa y proyecto compartido, visible en las prácticas, los rituales y las narrativas de la institución.'] }
  ],
  guia: {
    prop: 'Desarrollar en los docentes la capacidad de identificar y movilizar los recursos de resiliencia colectiva de sus comunidades educativas, y diseñar prácticas pedagógicas que construyan cotidianamente la base afectiva, relacional y simbólica de la paz.',
    adv: [
      'Esta competencia es especialmente sensible en contextos de conflicto armado, posconflicto o desplazamiento forzado. En estos contextos, el trabajo con memoria y resiliencia requiere acompañamiento psicosocial especializado.',
      'No confunda resiliencia con resignación: la resiliencia no implica aceptar pasivamente las injusticias, sino construir la fuerza colectiva necesaria para transformarlas.',
      'Los rituales de cierre y apertura colectivos (canciones, círculos, gestos simbólicos) son más poderosos de lo que parecen — son el suelo cotidiano de la resiliencia. No los subestime por parecer "simples".',
      'Cuide al facilitador: trabajar resiliencia comunitaria puede remover las propias heridas del docente. Asegúrese de que los docentes tengan sus propios espacios de cuidado y acompañamiento.'
    ],
    mat: ['Papel grande para la cartografía de resiliencia', 'Selección de testimonios de resiliencia comunitaria colombiana', 'Protocolo de círculo restaurativo (adaptado por nivel)', 'Materiales para construir el Árbol de los Deseos o el Mural del Cuidado'],
    cierre: 'Cierre con el ritual de la "Red de Resiliencia": cada participante toma un extremo de un hilo y lo pasa a otro mientras nombra una fortaleza del colectivo presente. Al final, todos sostienen la red tejida y el facilitador señala: así se ve la resiliencia comunitaria — no en cada persona sola, sino en lo que construimos juntos.'
  }
}

]; // fin _cse_data

_cse_data.forEach(function(item) { CSE.push(item); });
